All changes according to the comments in the excel
Artdianic94/PracticalTask pull request #7
Opened 2023-03-01 12:41 UTC by Artdianic94

lombok and email/password in Jenkinsfile haven't been deleted because they may be useful in solving the problem with credentials

2023-03-02 09:23 UTC, rmarchuk requested changes

2023-03-02 09:23 UTC, rmarchuk commented on src/test/java/pages/AmazonAddToCartPage.java
> +            driver.findElements(IPHONE_IN_LIST).get(i).click();
why do we need `findElements` each time?

2023-03-02 09:23 UTC, rmarchuk commented on src/test/java/pages/AmazonAddToCartPage.java
> +
empty string

2023-03-02 09:23 UTC, rmarchuk commented on src/test/java/pages/AmazonAddToCartPage.java
> +        productAddedToCart = driver.findElement(PRODUCT_TITLE).getText();
we find element only for logging product name - it is redundant

2023-03-02 09:23 UTC, rmarchuk commented on src/test/java/pages/AmazonAddToCartPage.java
> +            isTickIconGreen();
what is the purpose of this method? `isTickIconGreen()` is not used anywhere

2023-03-02 09:23 UTC, rmarchuk commented on src/test/java/pages/AmazonAddToCartPage.java
>      public boolean isTickIconGreen() {
method name is `isTickIconGreen` but it is checking text "Added"

2023-03-02 09:23 UTC, rmarchuk commented on src/test/java/pages/AmazonAddToCartPage.java
> +        boolean isTickIconGreen;
the following 8 lines may be replaced with just `return alertText.contains("Added");`

2023-03-02 09:23 UTC, rmarchuk commented on src/test/java/pages/AmazonAddToCartPage.java
> +    private final By IPHONE_IN_LIST = By.xpath("(//div[@class='a-section']//span[contains(text(), 'iPhone')])");
there is the same locator on AmazonSearchPage

2023-03-02 09:23 UTC, rmarchuk commented on src/test/java/tests/AmazonProductInCartTest.java
> +        boolean actualProduct = amazonAddToCartPage.doesCartContainSelectedProduct();
name of variable doesn't represent its content. we can just don't use variable here at all

2023-03-03 09:05 UTC, Artdianic94 commented on build.gradle
> -//def amazonTest = tasks.register("amazonTest", Test) {
commented lines were deleted

2023-03-03 09:06 UTC, Artdianic94 commented on src/test/java/pages/BasePage.java
> +    public void openMainPage(String amazonUrl) {
method name was changed

2023-03-03 09:07 UTC, Artdianic94 commented on src/test/java/utilities/AfterEachExtension.java
> +    public void afterEach(ExtensionContext context) throws IOException {
exception was deleted

2023-03-03 09:07 UTC, Artdianic94 commented on src/test/java/pages/AmazonAddToCartPage.java
> +            driver.findElements(IPHONE_IN_LIST).get(i).click();
fixed

2023-03-03 09:07 UTC, Artdianic94 commented on src/test/java/pages/AmazonAddToCartPage.java
> +
empty string was deleted

2023-03-03 09:08 UTC, Artdianic94 commented on src/test/java/pages/AmazonAddToCartPage.java
> +            isTickIconGreen();
this method was changed completely

2023-03-03 09:08 UTC, Artdianic94 commented on src/test/java/pages/AmazonAddToCartPage.java
>      public boolean isTickIconGreen() {
fixed

2023-03-03 09:08 UTC, Artdianic94 commented on src/test/java/pages/AmazonAddToCartPage.java
> +        boolean isTickIconGreen;
fixed

2023-03-03 09:09 UTC, Artdianic94 commented on src/test/java/pages/AmazonAddToCartPage.java
> +    private final By IPHONE_IN_LIST = By.xpath("(//div[@class='a-section']//span[contains(text(), 'iPhone')])");
fixed

2023-03-03 09:09 UTC, Artdianic94 commented on src/test/java/tests/AmazonProductInCartTest.java
> +        boolean actualProduct = amazonAddToCartPage.doesCartContainSelectedProduct();
fixed

2023-03-03 12:49 UTC, Artdianic94 commented on src/test/java/pages/AmazonAddToCartPage.java
> +        productAddedToCart = driver.findElement(PRODUCT_TITLE).getText();
fixed

2023-03-07 07:16 UTC, rmarchuk commented on src/test/java/pages/AmazonAddToCartPage.java
> +            isTickIconGreen();
it is better to rename the method to `setAnotherTypeOfMessage` as the return type is void

2023-03-07 08:01 UTC, rmarchuk commented on src/test/java/pages/AmazonAddToCartPage.java
> +    private final By IPHONE_IN_LIST = By.xpath("(//div[@class='a-section']//span[contains(text(), 'iPhone')])");
I still can see duplicate

2023-03-07 08:01 UTC, rmarchuk commented
please add messages to all assertions in your tests

2023-03-07 08:02 UTC, rmarchuk requested changes
please add some more changes according to comments

2023-03-07 08:05 UTC, rmarchuk commented on src/test/java/pages/AmazonAddToCartPage.java
> +            return driver.findElement(TICK_ICON_IN_ALERT).getCssValue("background-position");
it is better to check `success` class of element

2023-03-07 08:56 UTC, rmarchuk commented
rename AddToCartPage -> ProductPage

2023-03-07 19:37 UTC, Artdianic94 commented on src/test/java/pages/AmazonAddToCartPage.java
> +            isTickIconGreen();
methods names were changed

2023-03-07 19:38 UTC, Artdianic94 commented on src/test/java/pages/AmazonAddToCartPage.java
> +    private final By IPHONE_IN_LIST = By.xpath("(//div[@class='a-section']//span[contains(text(), 'iPhone')])");
duplicates were excluded

2023-03-07 19:38 UTC, Artdianic94 commented on src/test/java/pages/AmazonAddToCartPage.java
> +            return driver.findElement(TICK_ICON_IN_ALERT).getCssValue("background-position");
Method with Tick was changed

2023-03-08 13:35 UTC, rmarchuk approved these changes

2023-03-08 13:35 UTC, merged