Driver factory branch
Artdianic94/PracticalTask pull request #9
Opened 2023-03-13 14:08 UTC by Artdianic94

Here I added a multi browsers

2023-03-24 13:38 UTC, rmarchuk requested changes

2023-03-24 13:38 UTC, rmarchuk commented on docker-compose.yml
> +  opera:
there is no need in opera support

2023-03-24 13:38 UTC, rmarchuk commented on config/browsers.json
> +  "opera": {
there is no need in opera support

2023-03-27 07:46 UTC, Artdianic94 commented on src/test/java/tests/TestBase.java
> +                driverType = null;
fixed

2023-03-27 08:49 UTC, Artdianic94 commented on src/test/java/tests/TestBase.java
> +    public void startBrowser() {
one line method was deleted

2023-03-27 08:50 UTC, Artdianic94 commented on src/test/java/tests/TestBase.java
> +    public void setUp(String browser) {
fixed

2023-03-27 08:50 UTC, Artdianic94 commented on src/test/java/factorydriver/DriverFactory.java
> +                throw new IllegalStateException("Unexpected driver type: " + type);
fixed

2023-03-27 08:51 UTC, Artdianic94 commented on src/test/java/factorydriver/RemoteDriverManager.java
> +            case "opera":
this case was deleted in another pull request

2023-03-27 08:51 UTC, Artdianic94 commented on src/test/java/factorydriver/RemoteDriverManager.java
> +            case "chrome":
code duplication was deleted in another pull request

2023-03-27 08:53 UTC, Artdianic94 commented on docker-compose.yml
> +  opera:
opera was deleted in another pull request

2023-03-27 08:53 UTC, Artdianic94 commented on config/browsers.json
> +  "opera": {
opera was deleted in another pull request

2023-03-28 08:06 UTC, rmarchuk approved these changes

2023-03-28 08:06 UTC, merged